### ISSUE TITLE
Search: intermittent `lunr is not defined` errors in production

### ISSUE THREAD

**Issue by rdela** [alex-shpak/hugo-book#79] opened 2019-09-15 21:29 UTC
Hello and thanks for such a great theme. In production I have been seeing intermittent errors with the new search field from #56.

When clicking in the search box, this error appears in console

```
Uncaught ReferenceError: lunr is not defined
    at search-data.min.[long hash].js:1
```

Then, for each character typed, this error is logged in console:

```
search.min.[long hash].js:4 
Uncaught TypeError: Cannot read property 'idx' of undefined
    at HTMLInputElement.search (search.min.[long hash].js:4)
```

Reloading the page usually fixes the issue, but I have seen it occur several times in a row. Seems to happen most often on the homepage, but I have been able to reproduce it on docs pages as well. Especially frequent on slower connections and when clicking quickly in the search field while the page is still loading. I have not been able to reproduce the error in development with `hugo server`, only in production.

I am building with `hugo --gc --minify -b $URL` and hosting on Netlify. Unfortunately, this codebase I am working on and the deployment are both private. If there is a public site aside from https://themes.gohugo.io/theme/hugo-book/ (which has the [`absURL` issue](https://github.com/alex-shpak/hugo-book/issues/56#issuecomment-522622095)), I would be happy to try and reproduce there, or can try to create a reduced test case if you like.

Loading `search.js` and `lunr.min.js` with `async` instead of `defer` seems to resolve the issue entirely.

So the diff would be:

`/layouts/partials/docs/html-head.html`

```diff
 {{ if default true .Site.Params.BookSearch }}
 {{- $searchJS := resources.Get "search.js" | resources.ExecuteAsTemplate "search.js" . | resources.Minify | resources.Fingerprint }}
-<script defer src="{{ $searchJS.RelPermalink }}" integrity="{{ $searchJS.Data.Integrity }}"></script>
+<script async src="{{ $searchJS.RelPermalink }}" integrity="{{ $searchJS.Data.Integrity }}"></script>
 {{ end }}
 
 <!-- Favicon -->
```

`/assets/search.js`

```diff
  function loadScript(src, callback) {
    const script = document.createElement("script");
-    script.defer = true;
+    script.async = true;
    script.src = src;
    script.onload = callback;

    document.head.append(script);
```

Should I open a PR with this change or do you see a better way to solve?

**Comment by alex-shpak** [comment] 2019-09-22 13:26
I feared this will happen when added search. Well, I think `async` would not solve it, because order of script loading matters in this case. `defer` should have worked on another hand, defering script execution and maintaining order of script. I will need to dig deeper.

Found some explanation on [SO](https://stackoverflow.com/questions/10808109/script-tag-async-defer)

**Comment by rdela** [comment] 2019-09-27 21:45
Not sure I follow your line of reasoning about execution order, because I think parsing order is what matters here. I think we have created a potential race condition by using `defer` that is resolved by switching to `async`. I was seeing the errors all the time with `defer` and have not seen any errors since switching to `async`. Once I switched to `async`, search went from being very flaky to working perfectly, no matter how slow the connection or how fast I started typing in the search box.

`async` and `defer` do not necessarily work the way people think, I find them both confusing, especially when loading scripts from other scripts. This article has a good explanation:
https://flaviocopes.com/javascript-async-defer/

In the "With async, in the head" section:

> The script is fetched asynchronously, and when it’s ready the HTML parsing is paused to execute the script, then it’s resumed.

In the generated source, I only have one search script in the head. At parse time, with `async`, HTML parsing pauses when it reaches `search.min.js` and begins executing it. This is key because we are going to add to that HTML and want parsing to stop while we manipulate the HTML and load in our scripts, otherwise maybe the `search-data.min.js` script tag ends up getting parsed before the `lunr.min.js`, despite source order. Essentially, any guarantees about execution order `defer` might make are moot if HTML is added after parse time begins. Same article linked above, in the "Blocking parsing" section:

> `async` blocks the parsing of the page while `defer` does not.

The `loadScript` calls in `search.js` happen whenever that script is executed. In this case I think you want to pause HTML parsing while that execution happens because if one manipulates the HTML as the browser is parsing it, there is a non-zero chance parsing has already passed the point in the HTML where the script has been added, and you may end up with the out of order errors:

```
Uncaught ReferenceError: lunr is not defined
    at search-data.min.[long hash].js:1
```

Here, `search-data.min.js` has executed before `lunr.min.js`. The fact that `lunr.min.js` is much bigger and might take slightly longer to load in probably does not help. Perhaps on larger sites with bigger `search-data.min.js` payloads than mine this would be less of an issue.

Here is what my `head` ends up looking like with `async`, unminified and tidied up ("[...]" parts are unimportant truncated or sensitive redacted parts):

```html
<head>
  <meta name="generator" content="Hugo 0.57.2">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <!-- [...] -->
  <script async="" src="/search.min.[...].js" integrity="sha256-[...]="></script>
  <link rel="icon" href="/favicon.png" type="image/x-icon">
  <script>try { if (typeof Navigator.prototype.sendBeacon === 'function') { Navigator.prototype.sendBeacon = function(url, data) { return true; }; } } catch (exception) { console.error(exception); }</script>
  <script async="" src="/lunr.min.js"></script>
  <script async="" src="/search-data.min.[...].js"></script>
</head>
```

**Comment by alex-shpak** [comment] 2019-10-01 11:36
Hi, okay, I see your point, but not sure that `async` would solve it. Issue with `async` is that there is not guarantee of parsing order, first loaded script will be parsed first. Therefore `search-data.js` might be parsed before `lunr.js`, leading to same error.
I'm quite sure that race happening while loading JS from webserver, not while adding `script` tag to DOM.

I was able to reproduce same issues on async as well 😞 
![image](https://user-images.githubusercontent.com/5515443/65957738-e9f0d500-e44d-11e9-86c5-3bbc19c184d3.png)
![image](https://user-images.githubusercontent.com/5515443/65957748-f37a3d00-e44d-11e9-9b1d-3ca535d48e7f.png)

Probably most reliable way would be to change `loadScript` to `Promise`.

Why I used `defer`: 
- it claims to keep parsing order in which scripts were added.
- It defers parsing to the end of page, speeding up loading.

And after reading article that you mentioned Im still not sure why `defer` fails 🤔 
Quote:

> Keeping things in order
> Another case pro defer: scripts marked async are executed in casual order, when they become available. Scripts marked defer are executed (after parsing completes) in the order which they are defined in the markup.

I think issue needs more investigation, but it's definitely a bug.

**Comment by alex-shpak** [comment] 2019-10-01 12:00
Radical solution: using hugo pipes combine `lunr.js` and `search-data.js` in one file.

Also after some investigation, this might be the root of problem:
![image](https://user-images.githubusercontent.com/5515443/65959346-01ca5800-e452-11e9-8caf-22187d2dddea.png)

`search-data.js` loaded from memory cache.

**Comment by alex-shpak** [comment] 2019-10-01 13:30
@rdela 
Can you please try to change 
https://github.com/alex-shpak/hugo-book/blob/master/assets/search.js#L59
to `script.async = false` and test it on your website?

**Comment by alex-shpak** [comment] 2019-10-11 21:58
I think I can't reproduce it after fix.
Will close it as solved, If you still get this issue, please drop a message and I will re-open.

**Closed by alex-shpak** 2019-10-11 21:58 UTC
Labels: bug

**Comment by rdela** [comment] 2019-10-12 01:41
Thanks Alex, I haven't gotten a chance to test it out yet, but disabling async load for dynamically inserted scripts with async false seems like it should work.
